nextcloud-releases/updater_server

config/config.php

Small Rebranding

---

README.md
config/config.php
src/Response.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/update.feature
tests/unit/ResponseTest.php

Commitwise reviewing is easier.
Tests fail for me locally, but I can't figure out why (even on master), lets see if travis passes

Update server improvements

---

config/config.php
src/Response.php
tests/integration/features/update.feature

* use the "latest" number for displaying and download URLs
* current NC 10.0.0 sends 9.1.0.16 as version ;)
* adjusted config.php accordingly
This properly works here with my instance.
cc @LukasReschke @nickvergessen

Add an internalVersion number to compare against the send version

---

.gitignore
config/config.php
tests/integration/features/update.feature

* based on #8 
* this worked for me locally here

showcase RC testing

---

src/Request.php

For https://github.com/nextcloud/server/issues/2385
cc @rullzer @LukasReschke

Fix missing channel for beta of 11

---

config/config.php
tests/integration/features/update.feature

RC2 for 10.0.2

---

.travis.yml
config/config.php
src/Request.php
src/Response.php
tests/data/config.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/update.feature
tests/unit/ConfigTest.php
tests/unit/RequestTest.php

Verify PHP version before proposing an update

---

config/config.php
tests/integration/features/update.feature

Deliver 10.0.2 to beta channel

---

config/config.php
tests/integration/features/update.feature

If somebody is on 11 RC or beta already let's deliver the newest version to them regardless on which channel they are.

Deliver 11 in all channels to existing 11 users

---

tests/integration/features/update.feature

Tests for #17 - they will succeed once the updater ships the stable release
cc @LukasReschke @rullzer

provide tests for #17

---

config/config.php
tests/integration/features/update.feature

Use new URL for Jos

---

config/config.php
tests/integration/features/update.feature

Deliver 11 final build to 11 RC users

---

config/config.php
tests/integration/features/update.feature

11 daily for 11 daily users

---

config/config.php
tests/integration/features/update.feature

Move to releases folder

---

config/config.php
tests/integration/features/update.feature

Final version increase

---

config/config.php
src/Response.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/update.feature
tests/unit/ResponseTest.php

Adds a config flag that allows specifying how many instances receive an update.

Add staged config flag

---

config/config.php
tests/integration/features/update.feature

The (not deployed) config was before assuming that the finals are already out. Lets go with a RC instead.

Update beta channel to RC

---

config/config.php
tests/integration/features/update.feature

Bump to latest minor releases

---

src/Request.php
src/Response.php
tests/integration/features/update.feature
tests/unit/ResponseTest.php

@MorrisJobke This test will fail. Until we have a fix :wink:

Add test for bug in PHP version detection

---

config/config.php
src/Response.php
tests/integration/features/update.feature

@MorrisJobke Care to give it a review?

20% for 11

---

config/config.php
tests/integration/features/update.feature

Serve 11 to 40% of the people

---

config/config.php
tests/integration/features/update.feature

Adjust to new 11.0.2 RC1

---

config/config.php
tests/integration/features/update.feature

Deliver 11 to 60%

---

config/config.php
tests/integration/features/update.feature

Add RC2 to beta channel

---

config/config.php
tests/integration/features/update.feature

Update to RC3

---

config/config.php
tests/integration/features/update.feature

Deliver 11.0.1 to 80% of 10.x users

---

config/config.php

@LukasReschke Do we want this?

allow to use the updater server with master dailies

---

config/config.php
tests/integration/features/update.feature

To 100% of beta users and 20% of other channels. We can increase that quite speedily after one day or so.

Deliver 11.0.2

---

.travis.yml

Manually require PHPUnit 5.7

---

config/config.php
tests/integration/features/update.feature

Serve 11.0.2 to 100% of users

---

config/config.php
src/Response.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/update.feature
tests/unit/ResponseTest.php

PR for the updater coming soon. But this one here can be reviewed independently :-)

Add support for adding a signature to the response

---

config/config.php
tests/integration/features/update.feature

Update betas to 11.0.3RC2

---

config/config.php
tests/integration/features/update.feature

Bump to 11.0.3 final for beta channel

---

config/config.php
tests/integration/features/update.feature

11.0.3, 10.0.5 and 9.0.58

---

config/config.php
tests/integration/features/update.feature

Deliver Nextcloud 12 to 10% of our beta channel users

---

config/config.php
tests/integration/features/update.feature

Deliver 12.0.0beta2 to 100% of beta users

---

config/config.php
tests/integration/features/update.feature

Update to beta 3

---

config/config.php
tests/integration/features/update.feature

12.0.0 Beta 4

---

config/config.php
tests/integration/features/update.feature

Nextcloud 12.0.0 RC1

---

config/config.php
tests/integration/features/update.feature

12.0.0 RC2

---

config/config.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/update.feature

Update to 12.0.0

---

config/config.php
tests/integration/features/update.feature

New golden master

---

config/config.php
tests/integration/features/update.feature

Deliver 12.0.0 to 15% of all users

---

config/config.php
tests/integration/features/update.feature

Properly separate 12 and 13 dailies

---

config/config.php
tests/integration/features/update.feature

Add 12.0.1 RC2 to beta channel

---

config/config.php
tests/integration/features/update.feature

Bump to final versions

---

config/config.php
tests/integration/features/update.feature

Disable automated updates to 12.0.1 for now

---

config/config.php
tests/integration/features/update.feature

Bump to 12.0.2

---

config/config.php
tests/integration/features/update.feature

Bump to 12.0.3 RC1

---

config/config.php
tests/integration/features/update.feature

v12.0.3 RC2

---

config/config.php
tests/integration/features/update.feature

Deliver 12.0.3 to beta channel

---

config/config.php
tests/integration/features/update.feature

New 12.0.3 build

---

config/config.php
tests/integration/features/update.feature

Another build with new hashes

---

config/config.php
tests/integration/features/update.feature

Time to move the rest of the 11.0.x users to 12. I suggest we move Production over to 12 as well next week?

move rest of 11 users to 12

---

config/config.php
tests/integration/features/update.feature

For https://github.com/nextcloud/server/pull/7225

12.0.4 RC1

---

config/config.php
tests/integration/features/update.feature

cc @rullzer @nickvergessen 
Deployed on internal updater server

Prepare 12.0.4 RC2

---

config/config.php
tests/integration/features/update.feature

12.0.4 RC3

---

config/config.php
tests/integration/features/update.feature

Deployed on internal updater server.
cc @jospoortvliet

13.0.0 beta 3

---

config/config.php
tests/integration/features/update.feature

Provide 11.0.7RC1 and 12.0.5 RC1

---

config/config.php
tests/integration/features/update.feature

Ships https://github.com/nextcloud/server/pull/7764 via the beta channel

13.0.0 RC1

---

config/config.php
tests/integration/features/update.feature

As discussed - cc @jospoortvliet and @rullzer

Ship 12.0.4 to 15% of stable11 production channel

---

config/config.php
tests/integration/features/update.feature

As nothing bad happened in the last 3 days: lets move on and get it to nearly 50% of all instances.
Ref #97

Ship 12 to 49% stable11 instances

---

config/config.php
tests/integration/features/update.feature

Final 11.0.7 & 12.0.5 to beta and stable channels

---

config/config.php
tests/integration/features/update.feature

13.0.0 RC 4

---

config/config.php
tests/integration/features/update.feature

* [ ] move 13.0.0 archives from `prereleases` to the `releases` folder on the download server
* [ ] merge this PR

13.0.0 release to 15% of stable channel

---

config/config.php
tests/integration/features/update.feature

Ship 13 to 100% of the stable channel

---

config/config.php
tests/integration/features/update.feature

Bring new major versions to stable channels

---

config/config.php
tests/integration/features/production.feature

Ship 13 on production 12 channel

---

config/config.php
tests/integration/features/beta.feature

13.0.3 RC 2

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Ref https://github.com/nextcloud/server/pull/9802
cc @blizzz @rullzer

Stop 13.0.3 deployment

---

config/config.php
tests/integration/features/beta.feature

Nextcloud 14.0.0 beta3

---

config/config.php
tests/integration/features/beta.feature

NC 14 Beta 4

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

13.0.6 & 12.0.11

---

config/config.php
tests/integration/features/beta.feature

https://github.com/nextcloud/server/pull/10861

14.0.0 RC 2

---

config/config.php
tests/integration/features/beta.feature

Probably should also add some to the stable channel but lets do that in a different PR

14 final to beta channel

---

config/config.php
tests/integration/features/stable.feature

Signed-off-by: Joas Schilling <coding@schilljs.com>

Release 14.0.0 to 15% of stable users

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/daily.feature

Signed-off-by: Joas Schilling <coding@schilljs.com>

Release 14.0.1RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Signed-off-by: Joas Schilling <coding@schilljs.com>

Release 14.0.1 to all 14.0.0 and 15% of 13.0.6

---

config/config.php

How about going to 50% 14.0.1? Or should we wait? Opinions?

bring 14.0.1 to 50% of 13.0.6 users

---

config/config.php

I would wait for one more week or until Friday to publish this. Then we can move forward with 15.

Publish 14.0.4 to all instances on production channel

---

config/config.php
tests/integration/features/stable.feature

Give 10% of 14 users Nc 15

---

config/config.php

Fix docs urls

---

config/config.php
tests/integration/features/beta.feature

15.0.1 RC 2, 14.0.5 RC 2 & 13.0.9 RC 2

---

config/config.php

Fix displayed version number

---

config/config.php

Reverts nextcloud/updater_server#177

Revert "Fix displayed version number"

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Reverts nextcloud/updater_server#176

Revert "13.0.9, 14.0.5, 15.0.1"

---

config/config.php
tests/integration/features/production.feature

Ship 15.0.4 on 14.0.x with production channel

---

config/config.php
tests/integration/features/production.feature

Ship new major version on production only on latest patch level

---

config/config.php
tests/integration/features/beta.feature

16.0.0 beta 2

---

config/config.php
tests/integration/features/beta.feature

14.0.9 RC 1

---

config/config.php
tests/integration/features/beta.feature

15.0.6 RC 1

---

config/config.php
tests/integration/features/beta.feature

16.0.0 RC2

---

config/config.php
tests/integration/features/beta.feature

Ship 16.0.0 RC 2 to 100 % of beta channel

---

config/config.php
tests/integration/features/beta.feature

Roll out 16.0.0 on beta channel

---

config/config.php
tests/integration/features/beta.feature

@jospoortvliet merge when ready

Deploy 16.0.0

---

config/config.php
tests/integration/features/stable.feature

Push 16 to 25% of the instances with 15 on the stable channel

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Update production with latest maintenance releases

---

config/config.php
tests/integration/features/stable.feature

Ship 16 to 100% of stable15

---

config/config.php
tests/integration/features/beta.feature

16.0.2RC1 15.0.9RC1 14.0.13RC1

---

config/config.php

Add RC in the version

---

.travis.yml

Update PHP version on CI to 7.2

---

config/config.php
tests/integration/features/beta.feature

14.0.14RC1

---

config/config.php
tests/integration/features/beta.feature

15.0.11RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

Maintenance releases live

---

config/config.php
tests/integration/features/beta.feature

17.0.0 beta 2

---

config/config.php
tests/integration/features/beta.feature

15.0.12 RC1

---

config/config.php
tests/integration/features/stable.feature

So here goes... #270 but then to 17.0.1.

17.0.1 to 60% of stable users

---

config/config.php
tests/integration/features/beta.feature

New tarball

---

config/config.php
tests/integration/features/beta.feature

New 18 beta2 tarball

---

config/config.php
tests/integration/features/beta.feature

17.0.2 RC1

---

config/config.php
tests/integration/features/beta.feature

16.0.7 RC1

---

config/config.php
tests/integration/features/beta.feature

15.0.14 RC1

---

config/config.php
tests/integration/features/beta.feature

18 RC2 - take 2

---

config/config.php
tests/integration/features/beta.feature

18.0.1 RC1

---

config/config.php
tests/integration/features/beta.feature

18.0.2 RC2

---

config/config.php
tests/integration/features/production.feature

Production updates

---

src/Response.php

Add enterprise channel

---

config/config.php

Bump dailies

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

18.0.1 final

---

config/config.php
tests/integration/features/stable.feature

18.0.1 to 10% of stable17 users

---

config/config.php
tests/integration/features/stable.feature

Signed-off-by: Joas Schilling <coding@schilljs.com>

Deliver 18 to 40%

---

config/config.php
tests/integration/features/stable.feature

Serve 18 to all of 17 on stable

---

config/config.php
tests/integration/features/beta.feature

18.0.2 RC1

---

config/config.php
tests/integration/features/beta.feature

17.0.4 RC1

---

config/config.php
tests/integration/features/beta.feature

16.0.9 RC1

---

config/config.php
tests/integration/features/beta.feature

16.0.9 RC2

---

config/config.php
tests/integration/features/beta.feature

17.0.4 RC2

---

config/config.php
tests/integration/features/beta.feature

18.0.4 RC1

---

config/config.php
tests/integration/features/beta.feature

17.0.6 RC1

---

config/config.php
tests/integration/features/beta.feature

Version 16.0.10 RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

Maintenance releases

---

config/config.php
tests/integration/features/beta.feature

16.0.11 RC1

---

config/config.php
tests/integration/features/beta.feature

17.0.7 RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

18.0.5 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

16.0.11 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

18.0.4 rollback

---

config/config.php
tests/integration/features/beta.feature

version 19.0.1RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

17.0.8 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

18.0.7 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/production.feature
tests/integration/features/stable.feature

19.0.1 final

---

config/config.php
tests/integration/features/stable.feature

Roll out 19 to 20% of stable18

---

config/config.php
tests/integration/features/stable.feature

Move more stable instances to 19

---

config/config.php

First releases on the new build system. So let me do a first test update on the internal updater server from 17.0.8 up to 19.0.2 RC1.

August maintenance releases - 17.0.9RC1, 18.0.8RC1, 19.0.2RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

17.0.9 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

18.0.8 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.2 final

---

config/config.php
tests/integration/features/stable.feature

18.0.8 => 19 100%

---

config/config.php
tests/integration/features/stable.feature

Push 17 to all 16 versions

---

config/config.php
tests/integration/features/beta.feature

19.0.3 RC1

---

config/config.php
tests/integration/features/beta.feature

17.0.9 RC1

---

config/config.php
tests/integration/features/beta.feature

17.0.10 RC1

---

config/config.php
tests/integration/features/beta.feature

18.0.10RC1

---

config/config.php
tests/integration/features/beta.feature

19.0.4 RC1

---

config/config.php
tests/integration/features/beta.feature

18.0.10 RC2

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

17.0.10 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

18.0.10 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.4 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

20.0.1 final

---

config/config.php
tests/integration/features/beta.feature

19.0.5 RC1

---

config/config.php
tests/integration/features/beta.feature

18.0.11 RC1

---

config/config.php
tests/integration/features/beta.feature

20.0.2 rc1

---

config/config.php
tests/integration/features/beta.feature

18.0.11 RC2

---

config/config.php
tests/integration/features/beta.feature

19.0.5 RC2

---

config/config.php
tests/integration/features/beta.feature

20.0.2 RC2

---

config/config.php

Properly add RC

---

config/config.php
tests/integration/features/stable.feature

20% of 19 to 20.0.2

---

tests/integration/features/stable.feature

[production] 20% of 19 to 20.0.2

---

config/config.php
tests/integration/features/beta.feature

19.0.6 RC2

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

20.0.3 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.6 final

---

config/config.php
tests/integration/features/beta.feature

18.0.13 RC1

---

config/config.php
tests/integration/features/beta.feature

19.0.7 RC1

---

config/config.php
tests/integration/features/beta.feature

20.0.5 RC1

---

config/config.php
tests/integration/features/beta.feature

20.0.5 RC2

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

18.0.13 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.7 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

20.0.5 final

---

config/config.php
tests/integration/features/beta.feature

20.0.6 RC1

---

config/config.php
tests/integration/features/beta.feature

19.0.8 RC1

---

config/config.php
tests/integration/features/beta.feature

18.0.14 RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

18.0.14 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.8 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

20.0.6 final

---

config/config.php
tests/integration/features/beta.feature

20.0.7 RC1

---

config/config.php
tests/integration/features/beta.feature

20.0.8 RC1

---

config/config.php
tests/integration/features/beta.feature

19.0.9 RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.9 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

20.0.8 final

---

config/config.php
tests/integration/features/beta.feature

19.0.10 RC1

---

config/config.php
tests/integration/features/beta.feature

20.0.9 RC1

---

config/config.php
tests/integration/features/beta.feature

21.0.1 RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

19.0.10 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

20.0.9 final

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

21.0.1 final

---

config/config.php
tests/integration/features/stable.feature

Rollout 21 to 30%

---

config/config.php
tests/integration/features/beta.feature

21.0.2 RC1

---

config/config.php
tests/integration/features/beta.feature

20.0.10 RC1

---

config/config.php
tests/integration/features/beta.feature

19.0.11RC1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

https://github.com/nextcloud/server/issues/27037
https://github.com/nextcloud/server/pull/26825

Revert 19.0.11 update

---

config/config.php
tests/integration/features/stable.feature

Deliver 20 to 19.0.12

---

config/config.php
tests/integration/features/beta.feature

Reverts nextcloud/updater_server#581

Revert "22.0.0 beta 2 to production"

---

.gitignore
config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Put 21.0.3 on stable channels

---

config/config.php
tests/integration/features/stable.feature

Fix 20 eol

---

config/config.php
tests/integration/features/beta.feature

20.0.12rc1

---

config/config.php
tests/integration/features/beta.feature

22.1.0rc1 fix

---

config/config.php
tests/integration/features/daily.feature

Update daily builds

---

config/config.php
tests/integration/features/beta.feature

22.1.0 final

---

config/config.php
tests/integration/features/beta.feature

20.0.12 final

---

config/config.php
tests/integration/features/beta.feature

21.0.4 final

---

config/config.php
tests/integration/features/beta.feature

Fix 22.1.0

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Move 20.0.12, 21.0.4 and 22.1.0 to stable channel

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Move 20.0.12, 21.0.4 and 22.1.0 to stable channel production

---

config/config.php
tests/integration/features/stable.feature

Put 21 at 30% to 22

---

config/config.php
tests/integration/features/stable.feature

I hope that does not interfere with future merging of master to prod :)

[prod] Announce 21 only for instances on 20.0.12

---

config/config.php
tests/integration/features/stable.feature

offer NC 22 to 30%

---

.github/workflows/command-rebase.yml

23.0.0 beta 2 to production

---

config/config.php
tests/integration/features/beta.feature

23.0.0beta3

---

config/config.php
tests/integration/features/beta.feature

20.0.14rc1

---

config/config.php
tests/integration/features/beta.feature

Add 22.2 to 23 upgrade path

---

config/config.php
tests/integration/features/beta.feature

https://github.com/nextcloud/server/pull/29551

Fix 21.0.6rc1 signature

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

22.2.3 & 21.0.7

---

config/config.php
tests/integration/features/beta.feature

Fix beta signatures

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

download url for 23 moved to releases

---

config/config.php
tests/integration/features/beta.feature

23.0.1rc1, 22.2.4rc1 & 21.0.8rc1

---

config/config.php
tests/integration/features/beta.feature

RC3s for 21.08, 22.2.4 and 23.0.1

---

.github/workflows/upgrade.yml

Still pass upgrades-summary if config did not changed

---

.github/workflows/behat.yml
.github/workflows/upgrade.yml

Add integration summary

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

21.08, 22.2.4 and 23.0.1 final

---

.github/workflows/upgrade.yml

Don't check against production pushes

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Reverts nextcloud/updater_server#703

Revert "[production] 21.08, 22.2.4 and 23.0.1 final "

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

this flag should also be set accordingly

mark 21 EOL

---

config/config.php
tests/integration/features/beta.feature

- was done to fetch up to date updater.phar

24 beta 3 rebuild

---

config/config.php
tests/integration/features/beta.feature

Signed-off-by: Arthur Schiwon <blizzz@arthur-schiwon.de>

24.0.0 RC3

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

also bumps update from 23 to 24 to 100%

22.2.9, 23.0.6, 24.0.2

---

.github/workflows/upgrade.yml
config/config.php
tests/integration/features/beta.feature

Reverts nextcloud/updater_server#757

Revert "[prod] 24.0.2, 23.0.6, 22.2.9 RC1s"

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

23.0.8, 24.0.4

---

config/config.php
tests/integration/features/stable.feature

Move 23.0.8 to 24

---

config/config.php
tests/integration/features/beta.feature

@nickvergessen @AndyScherzinger @PVince81 @nextcloud/server

25.0.0 beta 1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Known and expected failures
```
Upgrades / Upgrade from 25 to 25.0.0 beta 1 (pull_request) Failing after 3s 
Upgrades / Upgrade from 25 to 25.0.0 beta 1 (push) Failing after 4s 
```

[prod] 25.0.0 beta 1

---

config/config.php
tests/integration/features/beta.feature

25.0.0 beta 2

---

config/config.php
tests/integration/features/beta.feature

23.0.11rc1, 24.0.7rc1, 25.0.1rc1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Leaving staged rollout to 25 at 30%, need to schedule bumping it

25.0.1, 24.0.7, 23.0.11

---

.github/workflows/upgrade.yml
config/config.php
tests/integration/features/beta.feature

(the branch is named after the final release date)

25.0.2 RC1, 24.0.8 RC1, 23.0.12 RC1

---

config/config.php
tests/integration/features/beta.feature

24.0.9rc1 & 25.0.3rc1

---

config/config.php
tests/integration/features/beta.feature

[prod] 26.0.0beta5

---

config/config.php
tests/integration/features/beta.feature

26.0.0 RC3, 25.0.5 RC1, 24.0.11 RC1

---

config/config.php
tests/integration/features/beta.feature

`26.0.1 RC1`, `25.0.6 RC1` and `24.0.12 RC1`

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

[prod] `26.0.1 RC1`, `25.0.6 RC1` and `24.0.12 RC1`

---

.github/workflows/behat.yml
config/config.php
tests/integration/features/beta.feature
tests/integration/features/daily.feature
tests/integration/features/stable.feature

https://github.com/nextcloud/updater_server/pull/856

[prod] `26.0.1`, `25.0.6` and `24.0.12`

---

config/config.php
tests/integration/features/beta.feature

27.0.0 RC1, 26.0.2 RC1, 25.0.7 RC 1

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

25.0.7, 26.0.2, 27.0.0 RC 2

---

.github/CODEOWNERS
config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

[prod] 27.0.0rc3

---

.github/workflows/behat.yml
.github/workflows/command-rebase.yml
.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/lint-php.yml
.github/workflows/upgrade.yml

chore(ci): upgrade workflows 

---

config/config.php
tests/integration/features/beta.feature

[prod] 27.1.0beta3

---

config/config.php
tests/integration/features/beta.feature

I am also removing the in-between stop step at 27.0.2. Discussed this with Barth the other day.

27.1.0 RC4

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

[prod] 25.0.13rc2, 26.0.8rc2 & 27.1.3rc2

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

[prod] 27.1.3, 26.0.8 and 25.0.13 finals

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

https://github.com/nextcloud-releases/updater_server/pull/969

[prod] 28.0.1rc1

---

.github/workflows/upgrade.yml

Should cancel ongoing runs on rebase and push

feat(workflows): add concurrency to upgrades

---

config/config.php
tests/integration/features/beta.feature

February 2024 rc1 releases

---

config/config.php
tests/integration/features/beta.feature

28.0.3 RC2, 27.1.7 RC2 and 26.0.12 RC2

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

https://github.com/nextcloud-releases/updater_server/pull/1021

[prod] March 2024 - 28.0.4, 27.1.8 & 26.0.13

---

.github/workflows/prerelease-dir-check.yml

Error case tested in https://github.com/nextcloud-releases/updater_server/pull/1044

feat(CI): Add github action to help ourselves with the URLs

---

config/config.php
tests/integration/features/beta.feature
tests/integration/features/stable.feature

29.0.1 & 28.0.6

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/stable.feature

Signed-off-by: Benjamin Gaussorgues <benjamin.gaussorgues@nextcloud.com>

[Prod] 27.1.10

---

build/config_builder
config/config.php

Add quotes for major versions
Add settings again

feat(builder): stay closer to original config.php

---

config/config.php
config/releases.json
tests/integration/features/beta.feature

chore: 28.0.9rc1 and 29.0.5rc1

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/stable.feature

This reverts commit e121a4e33b59f31c6edd6c6ed38ddcac0de1a0ca.
Due to a regression with the PDF viewer.

Revert "29.0.9"

---

config/config.php
config/releases.json
tests/integration/features/beta.feature

30.0.3 RC1, 29.0.10 RC1 and 28.0.13 RC1

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/daily.feature
tests/integration/features/stable.feature

Due to a regression in file sharing 
Hotfix expected for today

Revert 28.0.13 and 30.0.3

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/daily.feature
tests/integration/features/stable.feature

Due to a regression in file sharing
Hotfix expected for today

[prod] Revert 28.0.13 and 30.0.3

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/stable.feature

29.0.11, 30.0.5 & 31.0.0 beta 4

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/latest.feature

29.0.12 RC1, 30.0.6 RC1 and 31.0.0 RC3

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/latest.feature

31.0.1rc1, 30.0.7rc1 and 29.0.13rc1

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/daily.feature
tests/integration/features/latest.feature
tests/integration/features/stable.feature

chore: 29.0.15, 30.0.9 and 31.0.3

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/daily.feature
tests/integration/features/latest.feature
tests/integration/features/stable.feature

[prod] chore: 29.0.15, 30.0.9 and 31.0.3 

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/latest.feature

Second round of April 2025 RCs

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/latest.feature
tests/integration/features/stable.feature

`31.0.4` / `30.0.10` / `29.0.16`

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/latest.feature
tests/integration/features/stable.feature

chore: 30.0.11 and 31.0.5

---

config/config.php
config/releases.json
tests/integration/features/beta.feature
tests/integration/features/latest.feature

chore: 31.0.6rc2 & 30.0.12rc2

---

tests/integration/features/beta.feature

Seems the exception wasn't reported as failing test…

fix(tests): beta URL in features
